name: ui-automation

on:
  pull_request:
    branches:
      - develop

jobs:

  e2e-automation:
    name: E2E Selenium Automation
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout decent-app
        uses: actions/checkout@v4

      - name: Checkout automation repo
        uses: actions/checkout@v4
        with:
          repository: cbajandas/decent-ui-automation
          path: decent-ui-automation

      - name: Install dependencies
        run: |
          cd decent-ui-automation
          npm ci

      - name: Kill any leftover Chrome processes
        run: pkill chrome || true

      - name: Run Selenium tests
        run: |
          cd decent-ui-automation
          npm run test:single tests/multisig/app-homepage/content-loads.test.ts

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-results
          path: decent-ui-automation/test-results/

      - name: List test results files
        run: ls -l decent-ui-automation/test-results/ || true

      - name: Comment results on PR
        if: github.event_name == 'pull_request' && hashFiles('decent-ui-automation/test-results/test-results-summary.html') != ''
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: decent-ui-automation/test-results/test-results-summary.html
