name: UI Automation

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  wait-for-cloudflare-deployment:
    name: Wait for Cloudflare Pages Deployment
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.get_preview_info.outputs.url }}
      deployment_ready: ${{ steps.wait_for_deployment.outputs.ready }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for Cloudflare Pages deployment
        id: wait_for_deployment
        uses: fountainhead/action-wait-for-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Cloudflare Pages"
          ref: ${{ github.event.pull_request.head.sha }}
          timeoutSeconds: 600
          intervalSeconds: 10

      - name: Install dependencies
        run: npm ci

      - name: Install ts-node for script execution
        run: npm install --no-save ts-node

      - name: Extract Preview URL
        id: get_preview_info
        if: steps.wait_for_deployment.outputs.conclusion == 'success'
        run: |
          npx ts-node --compiler-options='{"module":"commonjs","target":"es2020","esModuleInterop":true}' .github/scripts/extract-preview-url.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}

  detect-preview-deployment:
    name: Detect Preview Deployment
    runs-on: ubuntu-latest
    needs: wait-for-cloudflare-deployment
    if: needs.wait-for-cloudflare-deployment.outputs.deployment_ready == 'true'
    outputs:
      preview_url: ${{ needs.wait-for-cloudflare-deployment.outputs.preview_url }}
      pr_number: ${{ github.event.pull_request.number }}
      should_run: ${{ needs.wait-for-cloudflare-deployment.outputs.preview_url != '' && 'true' || 'false' }}

    steps:
      - name: Output deployment info
        run: |
          echo "Preview URL: ${{ needs.wait-for-cloudflare-deployment.outputs.preview_url }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"

  e2e-automation:
    name: E2E Selenium Automation
    needs: detect-preview-deployment
    runs-on: ubuntu-latest
    if: needs.detect-preview-deployment.outputs.should_run == 'true'
    continue-on-error: true
    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci

      - name: Kill any leftover Chrome processes
        run: pkill chrome || true

      - name: Run Selenium tests
        env:
          BASE_URL: ${{ needs.detect-preview-deployment.outputs.preview_url }}
        run: |
          npm test
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-results
          path: test-results/

      - name: Prepend artifact link to summary
        run: |
          echo "[⬇️ Download Selenium Test Artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" | cat - test-results/test-results-summary.md > test-results/test-results-summary.with-link.md

      - name: Comment results on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ needs.detect-preview-deployment.outputs.pr_number }}
          path: test-results/test-results-summary.with-link.md
